version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: shopping-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 148779500
      POSTGRES_DB: shopping_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./shopping_server
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./shopping_server/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - FRONTEND_URL=http://161.97.66.168:5173 # מומלץ לעדכן גם כאן
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./shopping_app
      args:
        # כאן קורה הקסם: זה מעביר את ה-IP לתוך תהליך הבנייה
        - VITE_API_URL=http://161.97.66.168:3000 
    container_name: shopping-frontend
    ports:
      - "5173:5173"
    # משאירים גם כאן ליתר ביטחון
    environment:
      - VITE_API_URL=http://161.97.66.168:3000
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: