name: Remote Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: shimon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/shoppingApp
            git reset --hard HEAD
            git pull origin main
            docker compose up -d --build